### ISSUE TITLE
App usage values too high

### ISSUE THREAD

**Issue by zubyj** [icare-app/icare-client#2]
Electron takes a snapshot of running apps which includes the time they have  been open. The screentime is being stored in the database roughly every 10 seconds. However, the snapshot time isn't reset so the value aggregates.

**Comment by zubyjaved** [comment]
Solution idea

A running snapshot is stored with a unique string. Every time the database receives a screenTime update, the db checks the unique string. If the string is the same, aggregate the db with new value. else replace it.

**Comment by zubyjaved** [comment]
**Algorithm for pushing app time to database**

1. If app time = 0, do nothing
2. Else newestAppTime is difference between last recorded apptime and the newest apptime
3. Push the newestAppTime to database 
4. newestAppTime = appTime

**Comment by zubyj** [comment]
Resolved 

https://github.com/icare-app/icare-client/pull/4
